[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelins/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]